/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tragamonedas;

import ActionListeners.Deteccion;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import JFrames.CuadroStandard;
import Persona.Cliente.Cliente;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import Casino.Casino;

/**
 * La clase que contiene todo lo referente a la interfaz grafica del juego
 *
 * @author Equipo 2
 */
public class Tragaperras extends JFrame implements CuadroStandard {

    Deteccion detector;
    Cliente jugador;
    Casino casino;
    Figuras jfa = new Figuras();
    Figuras jfb = new Figuras();
    Figuras jfc = new Figuras();
    static public int apu;

    /**
     * Constructor de la clase
     * Tiene funciones para darle una mejor forma a la interfaz
     */
    public Tragaperras() {
        initComponents();
        setTitle("Tragaperras v1.0");
        apu = 0;
        Apuesta.setText(String.valueOf(apu));
        Figua.add(jfa);
        Figub.add(jfb);
        Figuc.add(jfc);
        jButton5.addActionListener(detector);
        establecerIcono(RUTA_ICONO);
        setSize(ANCHO, LARGO);
        setTitle(TITULO);
        getContentPane().setBackground(COLOR_FONDO);
        setLocationRelativeTo(null);
        setLayout(null);
        setVisible(true);
        setPreferredSize(new Dimension(ANCHO, LARGO));
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setResizable(false);
        jButton1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);
        jButton2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
        jButton3.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jButton3.setOpaque(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setBorderPainted(false);
        jButton4.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jButton4.setOpaque(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setBorderPainted(false);
        jButton5.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jButton5.setOpaque(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setBorderPainted(false);
        repaint();
    }
     /**
     * Setter del atributo detector.
     * @param detector valor para el atributo detector.
     */
    public void setDetector(Deteccion detector) {
        this.detector = detector;
    }
     /**
     * Setter del atributo jugador.
     * @param jugador valor para el atributo jugador.
     */
    public void setJugador(Cliente jugador) {
        this.jugador = jugador;
        Credito.setText(String.valueOf(jugador.fichas));
    }
     /**
     * Setter del atributo casino.
     * @param casino valor para el atributo casino.
     */
    public void setCasino(Casino casino) {
        this.casino = casino;
    }
    
     /**
      * Metodo para establecer el icono del casino
     */
    @Override
    public void establecerIcono(String ruta) {
        Image icon = new ImageIcon(getClass().getResource(ruta)).getImage();
        this.setIconImage(icon);
    }
     /**
      * Metodo para desplegar el panel
     */
    @Override
    public void desplegar() {
        this.setVisible(true);
    }
     /**
      * Metodo para esconder el panel
     */
    @Override
    public void esconder() {
        this.setVisible(false);
    }
     /**
      * Metodo para cerrar el panel
     */
    @Override
    public void cerrar() {
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }
     /**
      * Metodo para cambiar el panel
     */
    @Override
    public void cambiarPanel(JPanel panel) {
        setContentPane(panel);
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        B10 = new javax.swing.JLabel();
        Apuesta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Credito = new javax.swing.JLabel();
        Figua = new javax.swing.JPanel();
        Figub = new javax.swing.JPanel();
        Figuc = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));

        jPanel2.setBackground(new java.awt.Color(32, 4, 36));
        jPanel2.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 13)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("100");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 60, 20));

        jLabel7.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 13)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("10");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 60, 20));

        jLabel5.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 13)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("1000");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 60, 20));

        jLabel4.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Inicio");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 60, 20));

        B10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        B10.setForeground(new java.awt.Color(240, 240, 240));
        B10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B10.setText("Apuesta");
        jPanel2.add(B10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 60));

        Apuesta.setBackground(new java.awt.Color(102, 51, 255));
        Apuesta.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Apuesta.setForeground(new java.awt.Color(255, 0, 0));
        Apuesta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Apuesta.setText("100");
        jPanel2.add(Apuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Credito");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 200, 60));

        Credito.setBackground(new java.awt.Color(102, 51, 255));
        Credito.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Credito.setForeground(new java.awt.Color(255, 0, 0));
        Credito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Credito.setText("1000");
        jPanel2.add(Credito, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 200, 50));

        javax.swing.GroupLayout FiguaLayout = new javax.swing.GroupLayout(Figua);
        Figua.setLayout(FiguaLayout);
        FiguaLayout.setHorizontalGroup(
            FiguaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        FiguaLayout.setVerticalGroup(
            FiguaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel2.add(Figua, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 280, 65, 90));

        Figub.setPreferredSize(new java.awt.Dimension(67, 90));

        javax.swing.GroupLayout FigubLayout = new javax.swing.GroupLayout(Figub);
        Figub.setLayout(FigubLayout);
        FigubLayout.setHorizontalGroup(
            FigubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        FigubLayout.setVerticalGroup(
            FigubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel2.add(Figub, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 280, 65, 90));

        javax.swing.GroupLayout FigucLayout = new javax.swing.GroupLayout(Figuc);
        Figuc.setLayout(FigucLayout);
        FigucLayout.setHorizontalGroup(
            FigucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        FigucLayout.setVerticalGroup(
            FigucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel2.add(Figuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 280, 65, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tragamonedas/tragaperras.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        jButton5.setBackground(new java.awt.Color(0, 0, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Regresar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, -1, 30));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 50, 20));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 40, 30));

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 60, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     /**
      * Metodo principal para inciar el tragamonedas
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        if (apu <= jugador.fichas) {
            Casilla pwA = new Casilla(jfa);
            pwA.execute();

            Casilla pwB = new Casilla(jfb);
            pwB.execute();

            Casilla pwC = new Casilla(jfc);
            pwC.execute();

            Verificador cw = new Verificador(pwA, pwB, pwC, Credito, Apuesta, jButton1, jButton2, jButton3, jButton4, jugador, casino);
            cw.execute();
        } else {
            JOptionPane.showMessageDialog(this, "Credito insuficiente!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
     /**
      * Metodo para apostar 10
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        apu = apu + 10;
        if ((((float) (100 * apu) / jugador.fichas)) <= (jugador.apuestaMax * 100)) {
            if (apu <= jugador.fichas) {
                Apuesta.setText(String.valueOf(apu));
                repaint();
            } else {
                apu = apu - 10;
                JOptionPane.showMessageDialog(this, "Credito insuficiente!");
            }
        } else {
            apu = apu - 10;
            JOptionPane.showMessageDialog(this, "Llego a su limite de apuesta!");
        }

    }//GEN-LAST:event_jButton2ActionPerformed
     /**
      * Metodo para apostar 100
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        apu = apu + 100;
        if ((((float) (100 * apu) / jugador.fichas)) <= (jugador.apuestaMax * 100)) {
            if (apu <= jugador.fichas) {
                Apuesta.setText(String.valueOf(apu));
                repaint();
            } else {
                apu = apu - 100;
                JOptionPane.showMessageDialog(this, "Credito insuficiente!");
            }
        } else {
            apu = apu - 100;
            JOptionPane.showMessageDialog(this, "Llego a su limite de apuesta!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed
     /**
      * Metodo para apostar 1000
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        apu = apu + 1000;
        if ((((float) (100 * apu) / jugador.fichas)) <= (jugador.apuestaMax * 100)) {
            if (apu <= jugador.fichas) {
                Apuesta.setText(String.valueOf(apu));
                repaint();
            } else {
                apu = apu - 1000;
                JOptionPane.showMessageDialog(this, "Credito insuficiente!");
            }
        } else {
            apu = apu - 1000;
            JOptionPane.showMessageDialog(this, "Llego a su limite de apuesta!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed
     /**
      * Metodo para cambiar de panel
     */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        detector.setBoton(); // Regresar
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tragaperras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tragaperras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tragaperras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tragaperras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tragaperras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apuesta;
    private javax.swing.JLabel B10;
    private javax.swing.JLabel Credito;
    private javax.swing.JPanel Figua;
    private javax.swing.JPanel Figub;
    private javax.swing.JPanel Figuc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
